name: pbextensions
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/dvaruas/pbextensions

environment:
  sdk: ^3.7.2

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
